### ISSUE TITLE
Reactivity?

### ISSUE THREAD

**Issue by promentol** [cult-of-coders/morpher#4]
Does morpher package have reactivity support?

I see inside source code there is createReactiveQuery, but meanwhile in graphql definitions I see only Queries and Mutations.

Is there some documentation about this?

**Comment by theodorDiaconu** [comment]
@promentol that is dead code unfortunately. I couldn't find a good API design for this. I just don't want to do something that is written with few lines of code, and when you try to customize it you have to rewrite it.
